### PR TITLE
Add standalone python package for limesurvey etl, make ETL pipelines fully generic (not only CFE related), update DAG

### PR DESCRIPTION
**Pull request by tihartmann**

### CODE REVIEW

**Review by jannikrdev — APPROVED** [review]
That escalated quickly :smiley:

**Comment by tihartmann** [comment]
@lisallreiber @friep I added documentation (deployed it using GitHub pages, hope that's ok) and made some final changes

To dos:

- add last missing table based on @jannikrdev s script to `airflow/dags/configs/limesurvey_etl.yaml` to complete the CFE pipeline --> DONE
- add documentation for how to run a pipeline locally without airflow (and potentially a script that makes this process easier) --> DONE
- add unit (and integration?) tests --> DONE

**Comment by lisallreiber** [comment]
ich bin mir nicht sicher, ob wir die mappings open source stellen können. die diversitätskategorien von CFE sind zB trademarked...

**Comment by tihartmann** [comment]
> ich bin mir nicht sicher, ob wir die mappings open source stellen können. die diversitätskategorien von CFE sind zB trademarked...

Können wir gerne löschen, hat ja keinen Einfluss auf die Funktionalität der Applikation. :) Nur der CFE DAG funktioniert ohne die Mappings halt nicht, @lisallreiber

**Comment by lisallreiber** [comment]
> r

ich kann mal probieren die Beschriftungen abzuändern. Dann läuft die Pipeline mit synthetischen Beispiel Kategorien

**Comment by lisallreiber** [comment]
okay, I tried running an ETL pipeline locally: 

I think what is missing is instructions on how to set up a Postgres. Here is what I did:

**Step1: set up db on local machine for reporting**

```
source .env

docker run --name some-postgres -it -e POSTGRES_PASSWORD=$STAGING_DB_PASSWORD \
-e POSTGRES_USER=$STAGING_DB_USERNAME \
-e POSTGRES_DB=$(env STAGING_DB_NAME) \
-p 5432:5432 \
-d postgres
``` 

**Step2: run ETL locally**

then I think we need to let the people know in the documentation that there are some pre-defined DAGS in the airflow directory. Otherwise they won't know where to look for them. 

(here I found out that the argument needs to be step instead of steps (no s)

```
poetry run python -m limesurvey_etl --config_file airflow/dags/configs/cfe_limesurvey_meta_tables.yaml --step all
```

Here I ran into two errors: 

error1: fixed it by changing STAGING_DB_HOST in .env to localhost. Accoring to ChatGPT The error message indicates that the hostname "host.docker.internal" could not be resolved to an IP address. This hostname is often used to connect to the host machine from within a Docker container on Docker Desktop for Windows and Mac, but it's not available by default on Docker in Linux environments.

```
(psycopg2.OperationalError) could not translate host name "host.docker.internal" to address: nodename nor servname provided, or not known
```

error2
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/include/mappings/Mapping_LS-QuestionTypesMajor.csv'
```

so I did the config step again with just the extract step: this works
```
poetry run python -m limesurvey_etl --config_file airflow/dags/configs/cfe_limesurvey_meta_tables.yaml --step extract
```

Next step transform: 
```
poetry run python -m limesurvey_etl --config_file airflow/dags/configs/cfe_limesurvey_meta_tables.yaml --step transform
```

this is where the error happens.

So far for today. I will try to get back to this tomorrow

**Comment by tihartmann** [comment]
Hi @lisallreiber 
- If you like, you can add instructions on how to setup a local DB to the documentation ;) 
- I fixed the typo in the documentation, now it says `step` instead of `steps`. Good catch!
- The path to the mapping files is different when running the pipeline locally vs running it using Airflow. That caused your error. However, I optimized this so it now happens under the hood. Just pull the latest commit and you should be good to go 🙂

Note: when you run the pipeline, three schemas will be created in your PG DB: raw, staging, and reporting

**Comment by tihartmann** [comment]
closing this PR as dbt is introduced in a new PR to simplify the setup

**Pull request closed without merging**
